#+TITLE: Kill the noise

The appearance of the web democratized distribution. Democratization
led to abundance. But, there was a catch: the abundance paradox.

The paradox is that even though anyone can talk to everyone, it is
harder to find anyone worth paying attention to. This is why kids get
lost in crowds. Even though they know exactly what their parents look
like, it only takes a few minutes of distraction and noise for them
for them to get lost. And, just like in that analogy, getting lost on
the web can lead to terrifying outcomes---look at our attention span
lifespan, for starters.

Assuming the premise "signal is harder to make than noise" holds, it
is only natural for there to be more noise on the web.

Now, what I did not expect was that the democratization of knowledge
(as opposed to distribution) through artificial intelligence was going
to magnify the same paradox: now anyone can talk to everyone...about
anything. We have added another axis of complexity. Complexity
cubed. Yikes.

I want to counter-balance this. I am intentionally removing noise from
my life. This may be incorrect though. Perhaps, we should not try to
fight entropy, but the pursuit of simplicity is too enthralling.

The origin of this fascination comes from an attempt to not increase
what is already pretty high. Reality is already complex enough. It has
been thousands of years and we still do not understand what is going
on around us or between us. And when we think we do, we are mostly
assuming. Don't you think that we forget the fact that "walking" or
"talking" is an evolutionary miracle just too often?

So, coming back to noise. Why remove it? To grasp concepts
better. Understanding comes from the maximization of internalized
information. And internalization is faster when what we are trying to
understand is simple. Yet, comprehension alone is not enough, we
should strive for fast comprehension. Velocity, not position; slope,
not intercept.

Now, how can you understand faster if you cannot make yourself
smarter? Kill the noise.
